require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/availability_slots", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AvailabilitySlot. As you add validations to AvailabilitySlot, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AvailabilitySlot.create! valid_attributes
      get availability_slots_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      availability_slot = AvailabilitySlot.create! valid_attributes
      get availability_slot_url(availability_slot)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_availability_slot_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      availability_slot = AvailabilitySlot.create! valid_attributes
      get edit_availability_slot_url(availability_slot)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AvailabilitySlot" do
        expect {
          post availability_slots_url, params: { availability_slot: valid_attributes }
        }.to change(AvailabilitySlot, :count).by(1)
      end

      it "redirects to the created availability_slot" do
        post availability_slots_url, params: { availability_slot: valid_attributes }
        expect(response).to redirect_to(availability_slot_url(AvailabilitySlot.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AvailabilitySlot" do
        expect {
          post availability_slots_url, params: { availability_slot: invalid_attributes }
        }.to change(AvailabilitySlot, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post availability_slots_url, params: { availability_slot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested availability_slot" do
        availability_slot = AvailabilitySlot.create! valid_attributes
        patch availability_slot_url(availability_slot), params: { availability_slot: new_attributes }
        availability_slot.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the availability_slot" do
        availability_slot = AvailabilitySlot.create! valid_attributes
        patch availability_slot_url(availability_slot), params: { availability_slot: new_attributes }
        availability_slot.reload
        expect(response).to redirect_to(availability_slot_url(availability_slot))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        availability_slot = AvailabilitySlot.create! valid_attributes
        patch availability_slot_url(availability_slot), params: { availability_slot: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested availability_slot" do
      availability_slot = AvailabilitySlot.create! valid_attributes
      expect {
        delete availability_slot_url(availability_slot)
      }.to change(AvailabilitySlot, :count).by(-1)
    end

    it "redirects to the availability_slots list" do
      availability_slot = AvailabilitySlot.create! valid_attributes
      delete availability_slot_url(availability_slot)
      expect(response).to redirect_to(availability_slots_url)
    end
  end
end
